#!/usr/bin/env sh

__set() {
  if [[ -f "$1" ]]
  then 
    echo "export WALL=\"$1\"" > "$ENV_FILE"

    [[ -f "~/.wallpapers" ]] || [[ -d "~/.wallpapers" ]] || ln -sTf "$(dirname "$1")" ~/.wallpapers

    echo "#!/usr/bin/env bash" > "$BIN_FILE"
    if [[ $XDG_SESSION_TYPE -eq "wayland" ]]
    then
    echo swww img --transition-type wipe --transition-step 250 --transition-fps 60 $1 >> "$BIN_FILE"
    else  
    echo hsetroot -cover "$1" >> "$BIN_FILE"
    fi
  fi

  "$BIN_FILE"
}
