#!/usr/bin/env sh

set -e

# -- variables --

DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}"
WALLCTL_DIR="$DATA_DIR/wallctl"

mkdir -p "$WALLCTL_DIR"

BIN_FILE="$WALLCTL_DIR/.wallpaperset"
ENV_FILE="$WALLCTL_DIR/.wallpaperenv"

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/wallctl"
CONFIG_FILE="$CONFIG_DIR/daemon.json"

# -- utils --

msg() {
    printf "\033[32;1m%s\033[m %s\n" "$PROMPT" "$*"
}

warn() {
    >&2 printf "\033[33;1m%s \033[mwarning: %s\n" "$PROMPT" "$*"
}

die() {
    >&2 printf "\033[31;1m%s \033[merror: %s\n" "$PROMPT" "$*"
    exit 1
}

confirm() {
    >&2 printf "\033[33;1m%s \033[mconfirm? %s" "$PROMPT" "$CONFIRM_PROMPT"
    read -r ans
    if [ "$ans" != y ] ; then
        >&2 printf '%s\n' 'Exiting.'
        exit
    fi
}

has() {
  if ! command -v "$1" &>/dev/null; then
    return 1
  fi
}

# -- usage --

usage() {
>&2 cat <<"EOF"
  [current]  -  show current wallpaper
      [set]  -  set wallpaper [picture]
        [r]  -  randomize wallpaper [dir]
   [daemon]  -  start daemon [-f <config_file>]
EOF
exit 1
}

# -- main --

main() {
  [ "$1" ] || usage

  flag=${1#-}
  shift

  case $flag in
    current) __current $@;;
        set) __set $@ ;;
          r) __random $@ ;;
     daemon) __daemon $@ ;;
          *) die "command does not exist" ;;
  esac
}
